providers = ["python"]

[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step needed for FastAPI'"]

[start]
cmd = "uvicorn api_server:app --host=0.0.0.0 --port=$PORT"