#!/bin/bash
echo "🏗️ Starting Property Maintenance Tracker..."
echo "================================================"
echo ""
echo "🌐 Access your app at:"
echo "   📱 http://localhost:8080"
echo "   💻 http://127.0.0.1:8080"
echo ""
echo "🎯 For the best experience:"
echo "   ✅ Use Chrome, Safari, or Firefox"
echo "   ✅ Bookmark the URL for easy access"
echo "   ✅ Add to your home screen on mobile"
echo ""
echo "🚀 App Features:"
echo "   📋 Task Management Dashboard"
echo "   🍔 Left-side Navigation Menu"
echo "   📊 Google Sheets Integration"
echo "   🔔 Smart Notifications"
echo ""
echo "📖 Need help? Check public/README.txt"
echo "================================================"
echo "✨ Property Maintenance Tracker is now running!"

# Keep the script running
read -p "Press Enter to stop the server..."